// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"

	clients_service "github.com/fidesy-pay/facade/pkg/clients-service"
	crypto_service "github.com/fidesy-pay/facade/pkg/crypto-service"
	invoices_service "github.com/fidesy-pay/facade/pkg/invoices-service"
)

type Balance struct {
	Token      string  `json:"token"`
	Balance    float64 `json:"balance"`
	UsdBalance float64 `json:"usdBalance"`
}

type BalanceFilter struct {
	AddressEq string `json:"addressEq"`
	ChainEq   string `json:"chainEq"`
	TokenEq   string `json:"tokenEq"`
}

type CheckInvoiceInput struct {
	ID string `json:"id"`
}

type CheckInvoicePayload struct {
	Invoice *invoices_service.Invoice `json:"invoice"`
}

type ClientsFilter struct {
	UsernameIn []string `json:"username_in,omitempty"`
}

type ClientsPagination struct {
	Items []*clients_service.Client `json:"items,omitempty"`
}

type CreateInvoiceInput struct {
	UsdAmount float64 `json:"usd_amount"`
}

type CreateInvoicePayload struct {
	ID string `json:"id"`
}

type FeeFilter struct {
	ChainEq  string `json:"chainEq"`
	GasLimit *int   `json:"gasLimit,omitempty"`
}

type FeePayload struct {
	UsdAmount   float64 `json:"usd_amount"`
	TokenAmount float64 `json:"token_amount"`
}

type InvoicesFilter struct {
	IDIn       []string        `json:"idIn,omitempty"`
	ClientIDIn []string        `json:"clientIdIn,omitempty"`
	StatusIn   []InvoiceStatus `json:"statusIn,omitempty"`
}

type InvoicesPagination struct {
	Items []*invoices_service.Invoice `json:"items,omitempty"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginPayload struct {
	Token string `json:"token"`
}

type MainBalance struct {
	UsdBalance float64 `json:"usdBalance"`
}

type SendEmailOtpInput struct {
	Email string `json:"email"`
}

type SendEmailOtpPayload struct {
	EmailCodeID string `json:"email_code_id"`
}

type SignUpInput struct {
	EmailCodeID string `json:"email_code_id"`
	EmailCode   string `json:"email_code"`
	Username    string `json:"username"`
	Password    string `json:"password"`
	Email       string `json:"email"`
}

type SignUpPayload struct {
	Success bool `json:"success"`
}

type TransactionsFilter struct {
	AddressIn []string `json:"address_in,omitempty"`
}

type TransactionsPagination struct {
	Items []*crypto_service.Transaction `json:"items,omitempty"`
}

type TransferInput struct {
	ReceiverAddress  *string `json:"receiver_address,omitempty"`
	ReceiverClientID *string `json:"receiver_client_id,omitempty"`
	GasLimit         *int    `json:"gas_limit,omitempty"`
	GasPrice         *int    `json:"gas_price,omitempty"`
	TokenAmount      float64 `json:"token_amount"`
	Chain            string  `json:"chain"`
}

type TransferPayload struct {
	Hash string `json:"hash"`
}

type UpdateClientInput struct {
	IsInvoiceNotificationEnabled *bool `json:"is_invoice_notification_enabled,omitempty"`
}

type UpdateInvoiceInput struct {
	ID    string `json:"id"`
	Chain string `json:"chain"`
	Token string `json:"token"`
}

type UpdateInvoicePayload struct {
	Invoice *invoices_service.Invoice `json:"invoice"`
}

type WalletsFilter struct {
	ClientIDIn []string `json:"clientIdIn,omitempty"`
}

type WalletsPagination struct {
	Items []*crypto_service.Wallet `json:"items,omitempty"`
}

type Error string

const (
	ErrorNoAuth Error = "NO_AUTH"
)

var AllError = []Error{
	ErrorNoAuth,
}

func (e Error) IsValid() bool {
	switch e {
	case ErrorNoAuth:
		return true
	}
	return false
}

func (e Error) String() string {
	return string(e)
}

func (e *Error) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Error(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Error", str)
	}
	return nil
}

func (e Error) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type InvoiceStatus string

const (
	InvoiceStatusUnknownStatus   InvoiceStatus = "UNKNOWN_STATUS"
	InvoiceStatusNew             InvoiceStatus = "NEW"
	InvoiceStatusPending         InvoiceStatus = "PENDING"
	InvoiceStatusFailed          InvoiceStatus = "FAILED"
	InvoiceStatusSuccess         InvoiceStatus = "SUCCESS"
	InvoiceStatusExpired         InvoiceStatus = "EXPIRED"
	InvoiceStatusSendingToClient InvoiceStatus = "SENDING_TO_CLIENT"
	InvoiceStatusManualControl   InvoiceStatus = "MANUAL_CONTROL"
)

var AllInvoiceStatus = []InvoiceStatus{
	InvoiceStatusUnknownStatus,
	InvoiceStatusNew,
	InvoiceStatusPending,
	InvoiceStatusFailed,
	InvoiceStatusSuccess,
	InvoiceStatusExpired,
	InvoiceStatusSendingToClient,
	InvoiceStatusManualControl,
}

func (e InvoiceStatus) IsValid() bool {
	switch e {
	case InvoiceStatusUnknownStatus, InvoiceStatusNew, InvoiceStatusPending, InvoiceStatusFailed, InvoiceStatusSuccess, InvoiceStatusExpired, InvoiceStatusSendingToClient, InvoiceStatusManualControl:
		return true
	}
	return false
}

func (e InvoiceStatus) String() string {
	return string(e)
}

func (e *InvoiceStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InvoiceStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InvoiceStatus", str)
	}
	return nil
}

func (e InvoiceStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
