package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"fmt"

	"github.com/fidesy-pay/facade/internal/app/graph/generated"
	"github.com/fidesy-pay/facade/internal/pkg/middleware/auth"
	"github.com/fidesy-pay/facade/internal/pkg/model"
	clients_service "github.com/fidesy-pay/facade/pkg/clients-service"
)

// UpdateClient is the resolver for the updateClient field.
func (r *clientMutationsResolver) UpdateClient(ctx context.Context, obj *model.ClientMutations, input model.UpdateClientInput) (*clients_service.Client, error) {
	session := auth.GetSession(ctx)

	client, err := r.clientsClient.UpdateClient(ctx, &clients_service.UpdateClientRequest{
		Id:                           session.ClientID,
		IsInvoiceNotificationEnabled: input.IsInvoiceNotificationEnabled,
	})
	if err != nil {
		return nil, fmt.Errorf("clientsClient.UpdateClient: %w", err)
	}

	return client, nil
}

// RegenerateAPIKey is the resolver for the regenerateAPIKey field.
func (r *clientMutationsResolver) RegenerateAPIKey(ctx context.Context, obj *model.ClientMutations) (*clients_service.Client, error) {
	session := auth.GetSession(ctx)

	client, err := r.clientsClient.RegenerateAPIKey(ctx, &clients_service.RegenerateAPIKeyRequest{
		ClientId: session.ClientID,
	})
	if err != nil {
		return nil, fmt.Errorf("clientsClient.RegenerateAPIKey: %w", err)
	}

	return client, nil
}

// Deactivate is the resolver for the deactivate field.
func (r *clientMutationsResolver) Deactivate(ctx context.Context, obj *model.ClientMutations) (*clients_service.Client, error) {
	session := auth.GetSession(ctx)

	_, err := r.clientsClient.Deactivate(ctx, &clients_service.DeactivateRequest{
		ClientId: session.ClientID,
	})
	if err != nil {
		return nil, fmt.Errorf("clientsClient.Deactivate: %w", err)
	}

	return &clients_service.Client{Id: session.ClientID}, nil
}

// ClientMutations is the resolver for the clientMutations field.
func (r *mutationResolver) ClientMutations(ctx context.Context) (*model.ClientMutations, error) {
	return &model.ClientMutations{}, nil
}

// ClientMutations returns generated.ClientMutationsResolver implementation.
func (r *Resolver) ClientMutations() generated.ClientMutationsResolver {
	return &clientMutationsResolver{r}
}

type clientMutationsResolver struct{ *Resolver }
