package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"fmt"

	"github.com/fidesy-pay/facade/internal/pkg/model"
	clients_service "github.com/fidesy-pay/facade/pkg/clients-service"
)

// Clients is the resolver for the clients field.
func (r *queryResolver) Clients(ctx context.Context, filter *model.ClientsFilter, page int, perPage int) (*model.ClientsPagination, error) {
	clients, err := r.clientsClient.ListClients(ctx, &clients_service.ListClientsRequest{
		Filter: &clients_service.ListClientsRequest_Filter{
			UsernameIn: filter.UsernameIn,
		},
		Page:    uint64(page),
		PerPage: uint64(perPage),
	})
	if err != nil {
		return nil, fmt.Errorf("clientsClient.ListClients: %w", err)
	}

	return &model.ClientsPagination{
		Items: clients.GetClients(),
	}, nil
}
