package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"fmt"

	"github.com/fidesy-pay/facade/internal/pkg/model"
	email_service "github.com/fidesy-pay/facade/pkg/email-service"
)

// SendEmailOtp is the resolver for the sendEmailOtp field.
func (r *mutationResolver) SendEmailOtp(ctx context.Context, input model.SendEmailOtpInput) (*model.SendEmailOtpPayload, error) {
	resp, err := r.emailClient.SendCode(ctx, &email_service.SendCodeRequest{
		Email: input.Email,
	})
	if err != nil {
		return nil, fmt.Errorf("emailClient.SendCode: %w", err)
	}

	return &model.SendEmailOtpPayload{EmailCodeID: resp.GetId()}, nil
}
