package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"fmt"

	"github.com/fidesy-pay/facade/internal/pkg/model"
	crypto_service "github.com/fidesy-pay/facade/pkg/crypto-service"
	external_api "github.com/fidesy-pay/facade/pkg/external-api"
	"github.com/samber/lo"
	"golang.org/x/sync/errgroup"
)

// Fee is the resolver for the fee field.
func (r *queryResolver) Fee(ctx context.Context, filter *model.FeeFilter) (*model.FeePayload, error) {
	var (
		fee        int64
		tokenPrice float64
	)

	gasLimit := uint64(21000)
	if filter.GasLimit != nil {
		gasLimit = uint64(*filter.GasLimit)
	}

	errGroup := errgroup.Group{}

	errGroup.Go(func() error {
		feeResp, err := r.cryptoClient.SuggestFee(ctx, &crypto_service.SuggestFeeRequest{
			Chain:    filter.ChainEq,
			GasLimit: lo.ToPtr(gasLimit),
		})
		if err != nil {
			return fmt.Errorf("cryptoClient.SuggestFee: %w", err)
		}

		fee = int64(feeResp.GetFee())

		return nil
	})

	errGroup.Go(func() error {
		tokenPriceResp, err := r.externalAPI.GetPrice(ctx, &external_api.GetPriceRequest{
			Symbol: chainTokens[filter.ChainEq][0],
		})
		if err != nil {
			return fmt.Errorf("coinGeckoAPI.GetPrice: %w", err)
		}

		tokenPrice = tokenPriceResp.GetPriceUsd()

		return nil
	})

	if err := errGroup.Wait(); err != nil {
		return nil, err
	}

	return &model.FeePayload{
		UsdAmount:   tokenPrice * (float64(fee) / 1e18),
		TokenAmount: float64(fee) / 1e18,
	}, nil
}
