package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"fmt"

	"github.com/fidesy-pay/facade/internal/pkg/model"
	auth_service "github.com/fidesy-pay/facade/pkg/auth-service"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginPayload, error) {
	loginResp, err := r.authClient.Login(ctx, &auth_service.LoginRequest{
		Username: input.Username,
		Password: input.Password,
	})
	if err != nil {
		return nil, fmt.Errorf("authClient.Login: %w", err)
	}

	return &model.LoginPayload{
		Token: loginResp.Token,
	}, nil
}
