package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"errors"
	"fmt"

	"github.com/fidesy-pay/facade/internal/pkg/middleware/auth"
	clients_service "github.com/fidesy-pay/facade/pkg/clients-service"
)

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*clients_service.Client, error) {
	session := auth.GetSession(ctx)

	clients, err := r.clientsClient.ListClients(ctx, &clients_service.ListClientsRequest{
		Filter: &clients_service.ListClientsRequest_Filter{
			UsernameIn: []string{session.Username},
		},
	})
	if err != nil {
		return nil, fmt.Errorf("clientsClient.ListClients: %w", err)
	}

	if len(clients.Clients) == 0 {
		return nil, errors.New("client not found")
	}

	return clients.Clients[0], nil
}
