package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"fmt"

	"github.com/fidesy-pay/facade/internal/pkg/model"
	auth_service "github.com/fidesy-pay/facade/pkg/auth-service"
	clients_service "github.com/fidesy-pay/facade/pkg/clients-service"
	crypto_service "github.com/fidesy-pay/facade/pkg/crypto-service"
	email_service "github.com/fidesy-pay/facade/pkg/email-service"
)

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, input model.SignUpInput) (*model.SignUpPayload, error) {
	_, err := r.emailClient.ConfirmCode(ctx, &email_service.ConfirmCodeRequest{
		Id:   input.EmailCodeID,
		Code: input.EmailCode,
	})
	if err != nil {
		return nil, fmt.Errorf("emailClient.ConfirmCode: %w", err)
	}

	client, err := r.clientsClient.CreateClient(ctx, &clients_service.CreateClientRequest{
		Username: input.Username,
		Email:    input.Email,
	})
	if err != nil {
		return nil, fmt.Errorf("clientsClient.CreateClient: %w", err)
	}

	_, err = r.authClient.SignUp(ctx, &auth_service.SignUpRequest{
		Username: client.Username,
		Password: input.Password,
		ClientId: client.Id,
	})
	if err != nil {
		return nil, fmt.Errorf("authClient.SignUp: %w", err)
	}

	_, err = r.cryptoClient.CreateWallet(ctx, &crypto_service.CreateWalletRequest{
		ClientId: client.Id,
	})
	if err != nil {
		return nil, fmt.Errorf("cryptoClient.CreateWallet: %w", err)
	}

	return &model.SignUpPayload{Success: true}, nil
}
