package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"fmt"

	"github.com/fidesy-pay/facade/internal/pkg/middleware/auth"
	"github.com/fidesy-pay/facade/internal/pkg/model"
	crypto_service "github.com/fidesy-pay/facade/pkg/crypto-service"
)

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context, filter *model.TransactionsFilter, page int, perPage int) (*model.TransactionsPagination, error) {
	session := auth.GetSession(ctx)

	transactionsResp, err := r.cryptoClient.ListTransactions(ctx, &crypto_service.ListTransactionsRequest{
		Filter: &crypto_service.ListTransactionsRequest_Filter{
			ClientIdIn: []string{session.ClientID},
		},
		Page:    uint64(page),
		PerPage: uint64(perPage),
	})
	if err != nil {
		return nil, fmt.Errorf("cryptoClient.ListTransactions: %w", err)
	}

	return &model.TransactionsPagination{
		Items: transactionsResp.Transactions,
	}, nil
}
