package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"fmt"
	"time"

	"github.com/fidesy-pay/facade/internal/app/graph/generated"
	"github.com/fidesy-pay/facade/internal/pkg/loaders"
	"github.com/fidesy-pay/facade/internal/pkg/middleware/auth"
	clients_service "github.com/fidesy-pay/facade/pkg/clients-service"
	crypto_service "github.com/fidesy-pay/facade/pkg/crypto-service"
)

// Amount is the resolver for the amount field.
func (r *transactionResolver) Amount(ctx context.Context, obj *crypto_service.Transaction) (float64, error) {
	return float64(obj.Amount) / 1e18, nil
}

// CreatedAt is the resolver for the created_at field.
func (r *transactionResolver) CreatedAt(ctx context.Context, obj *crypto_service.Transaction) (*time.Time, error) {
	if obj == nil {
		return &time.Time{}, nil
	}

	time := obj.CreatedAt.AsTime()

	return &time, nil
}

// Sender is the resolver for the sender field.
func (r *transactionResolver) Sender(ctx context.Context, obj *crypto_service.Transaction) (*clients_service.Client, error) {
	clientID, err := loaders.For(ctx).ClientIDByAddressLoader.Load(ctx, obj.FromAddress)
	if err != nil {
		return nil, fmt.Errorf("ClientIDByAddressLoader: %w", err)
	}

	if clientID == "" {
		return &clients_service.Client{}, nil
	}

	return loaders.For(ctx).ClientByIDLoader.Load(ctx, clientID)
}

// Receiver is the resolver for the receiver field.
func (r *transactionResolver) Receiver(ctx context.Context, obj *crypto_service.Transaction) (*clients_service.Client, error) {
	clientID, err := loaders.For(ctx).ClientIDByAddressLoader.Load(ctx, obj.ToAddress)
	if err != nil {
		return nil, fmt.Errorf("ClientIDByAddressLoader: %w", err)
	}

	if clientID == "" {
		return &clients_service.Client{}, nil
	}

	return loaders.For(ctx).ClientByIDLoader.Load(ctx, clientID)
}

// IsClientSender is the resolver for the isClientSender field.
func (r *transactionResolver) IsClientSender(ctx context.Context, obj *crypto_service.Transaction) (bool, error) {
	session := auth.GetSession(ctx)

	clientID, err := loaders.For(ctx).ClientIDByAddressLoader.Load(ctx, obj.FromAddress)
	if err != nil {
		return false, fmt.Errorf("ClientIDByAddressLoader: %w", err)
	}

	return session.ClientID == clientID, nil
}

// Transaction returns generated.TransactionResolver implementation.
func (r *Resolver) Transaction() generated.TransactionResolver { return &transactionResolver{r} }

type transactionResolver struct{ *Resolver }
