package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"fmt"

	"github.com/fidesy-pay/facade/internal/pkg/middleware/auth"
	"github.com/fidesy-pay/facade/internal/pkg/model"
	crypto_service "github.com/fidesy-pay/facade/pkg/crypto-service"
)

// Transfer is the resolver for the transfer field.
func (r *mutationResolver) Transfer(ctx context.Context, input model.TransferInput) (*model.TransferPayload, error) {
	session := auth.GetSession(ctx)

	var (
		gasLimit uint64
		gasPrice uint64
	)

	if input.GasLimit != nil {
		gasLimit = uint64(*input.GasLimit)
	}

	if input.GasPrice != nil {
		gasPrice = uint64(*input.GasPrice)
	}

	transferResp, err := r.cryptoClient.Transfer(ctx, &crypto_service.TransferRequest{
		ClientId:         session.ClientID,
		ReceiverAddress:  input.ReceiverAddress,
		ReceiverClientId: input.ReceiverClientID,
		GasLimit:         &gasLimit,
		GasPrice:         &gasPrice,
		Amount:           input.TokenAmount,
		Chain:            input.Chain,
	})
	if err != nil {
		return nil, fmt.Errorf("cryptoClient.Transfer: %w", err)
	}

	return &model.TransferPayload{Hash: transferResp.GetTransactionHash()}, nil
}
